sudo: required
services:
  - docker
matrix:
  include:
    language: go
    go: 1.9.x
    before_install:
      - cd authen
    install:
      - make dependency
    env:
      global:
        - COMMIT=${TRAVIS_COMMIT::8}
    after_success:
      - make build
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - export REPO=muchrm/mis-backend/authen
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - make docker repo=$REPO commit=$COMMIT
      - docker tag $REPO:$COMMIT $REPO:$TAG
      - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $REPO
