version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
  workload:
    build: ./workload
    image: mis/workload
    container_name: mis-workload
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: workload.local
  db:
    image: mongo:3.4
    container_name: mis-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw
