version: '3.3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  workload:
    build: ./workload
    image: mis/workload
    container_name: mis-workload
    depends_on:
      - db
      - proxy
      - rabbitmq
    environment:
      VIRTUAL_HOST: workload.local

  personnel:
    build: ./personnel
    image: mis/personnel
    container_name: mis-personnel
    depends_on:
      - db
      - proxy
      - rabbitmq
    environment:
      VIRTUAL_HOST: personnel.local

  db:
    image: mongo:3.4
    container_name: mis-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
