version: '2.1'
services:
  consul:
    image: progrium/consul:latest
    container_name: consul
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  nginx-lb:
    build: nginx/
    container_name: nginx-lb
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    expose:
      - 8000
      - 8443
      - 8001
      - 8444
    links:
      - consul:consul
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"

  kong-database:
    image: postgres:10
    container_name: kong-db
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - ./backup/pg:/backup:rw
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    build: kong/
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
    links:
      - workload
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    command: -a mis=mis2017
    ports:
      - 9001:8080

  authen:
    build: authen/
    image: mis/authen
    container_name: mis-authen
    depends_on:
      - db
    volumes:
      - ./authen:/work:rw

  workload:
    build: workload/
    image: mis/workload
    container_name: mis-workload
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./workload:/work:rw

  upload:
    build: upload/
    image: mis/upload
    container_name: mis-upload
    volumes:
      - ./data/uploads:/work/uploads:rw

  personnel:
    build: personnel/
    image: mis/personnel
    container_name: mis-personnel
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./personnel:/work:rw

  db:
    image: mongo:3.4
    container_name: mis-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup/mongo:/backup:rw

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
